version: '3'

services:
  chat:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_IP=db
      - DB_PORT=3306
      - DB_DBNAME=city-db
      - DB_USER=root
      - DB_PASSWORD=tutorial0
    networks:
      - demo_net


networks:
  demo_net:
    external: true


