#version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'device-db'
      MYSQL_ROOT_PASSWORD: 'tutorial0'
    ports:
      - "3308:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - demo_net

#  reverse-proxy:
#    image: traefik:latest
#    command:
#      - --api.insecure=true
#      - --providers.docker
#      - --accesslog=true
#      - --accesslog.filepath=/var/log/traefik/access.log
#      - --log.level=DEBUG
#      - --entrypoints.web.address=:81
#
#    ports:
#      - "81:81"
#      - "8081:8081"
#
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - traefik_logs:/var/log/traefik
#
#    networks:
#      - demo_net

  devices:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    deploy:
      replicas: 4
#    ports:
#      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/device-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tutorial0
#      - DB_IP=db
#      - DB_PORT=3306
#      - DB_DBNAME=device-db
#      - DB_USER=root
#      - DB_PASSWORD=tutorial0

    networks:
      - demo_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.devices.rule=Host(`devices.localhost`) || PathPrefix(`/devices`)"
      - "traefik.http.middlewares.devices-strip.stripprefix.prefixes=/devices"
      - "traefik.http.routers.devices.middlewares=devices-strip "
      - "traefik.http.services.devices.loadbalancer.server.port=8081"


volumes:
  my-db:
  traefik_logs:

networks:
  demo_net:
    external: true







